version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env  # reads from root-level .env file
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SERVER_URL: http://localhost:5000
    environment:
      VITE_SERVER_URL: http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres-data:
